#include "../../test_suites.hpp"

const t_test_case *get_compiler_cobol_round_trip_pipeline_tests(size_t *count);

int test_cblc_copy_file_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_append_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_len_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_clear_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_empty_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_equals_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_equals_literal_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_capacity_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_starts_with_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_ends_with_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_compare_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_contains_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_equals_false_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_empty_false_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_starts_with_literal_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_ends_with_literal_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_compare_less_than_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_compare_greater_than_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_compare_literal_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_contains_false_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_contains_empty_literal_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_constructor_capacity_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_capacity_constructor_grows_for_assignment_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_capacity_constructor_grows_for_append_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_append_then_len_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_clear_then_empty_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_starts_with_false_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_ends_with_false_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_starts_with_empty_literal_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_ends_with_empty_literal_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_compare_shorter_prefix_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_compare_longer_prefix_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_contains_literal_false_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_copy_constructor_equals_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_literal_constructor_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_copy_constructor_translates_to_cobol_and_executes(void);
int test_cblc_inline_void_pointer_alloc_free_translates_to_cobol_and_executes(void);
int test_cblc_inline_int_pointer_index_translates_to_cobol_and_executes(void);
int test_cblc_inline_char_pointer_index_translates_to_cobol_and_executes(void);
int test_cblc_inline_pointer_arithmetic_translates_to_cobol_and_executes(void);
int test_cblc_inline_address_of_scalar_translates_to_cobol_and_executes(void);
int test_cblc_inline_pointer_return_translates_to_cobol_and_executes(void);
int test_cblc_inline_void_pointer_to_int_pointer_translates_to_cobol_and_executes(void);
int test_cblc_inline_int_pointer_to_void_pointer_translates_to_cobol_and_executes(void);
int test_cblc_inline_pointer_subtraction_translates_to_cobol_and_executes(void);
int test_cblc_inline_pointer_variable_offset_translates_to_cobol_and_executes(void);
int test_cblc_inline_char_pointer_dereference_translates_to_cobol_and_executes(void);
int test_cblc_inline_address_of_char_scalar_translates_to_cobol_and_executes(void);
int test_cblc_inline_local_pointer_declaration_translates_to_cobol_and_executes(void);
int test_cblc_inline_pointer_parameter_return_translates_to_cobol_and_executes(void);
int test_cblc_inline_realloc_pointer_translates_to_cobol_and_executes(void);
int test_cblc_inline_null_pointer_assignment_translates_to_cobol_and_executes(void);
int test_cblc_inline_pointer_offset_write_translates_to_cobol_and_executes(void);
int test_cblc_inline_pointer_argument_mutates_scalar_translates_to_cobol_and_executes(void);
int test_cblc_inline_pointer_argument_returns_same_pointer_translates_to_cobol_and_executes(void);
int test_cblc_inline_char_pointer_arithmetic_translates_to_cobol_and_executes(void);
int test_cblc_inline_char_pointer_return_translates_to_cobol_and_executes(void);
int test_cblc_inline_void_pointer_address_of_int_translates_to_cobol_and_executes(void);
int test_cblc_inline_realloc_int_pointer_writes_after_resize_translates_to_cobol_and_executes(void);
int test_cblc_inline_pointer_null_after_free_translates_to_cobol_and_executes(void);
int test_cblc_inline_std_strlen_empty_literal_translates_to_cobol_and_executes(void);
int test_cblc_inline_std_strlen_spaces_literal_translates_to_cobol_and_executes(void);
int test_cblc_inline_std_strlen_literal_translates_to_cobol_and_executes(void);
int test_cblc_inline_pointer_argument_mutates_allocated_element_translates_to_cobol_and_executes(void);
int test_cblc_inline_char_pointer_argument_mutates_scalar_translates_to_cobol_and_executes(void);
int test_cblc_inline_pointer_variable_subtraction_translates_to_cobol_and_executes(void);
int test_cblc_inline_local_char_pointer_declaration_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_clear_after_assignment_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_copy_constructor_len_translates_to_cobol_and_executes(void);
int test_cblc_inline_class_multiple_method_calls_translates_to_cobol_and_executes(void);
int test_cblc_inline_class_const_member_arithmetic_translates_to_cobol_and_executes(void);
int test_cblc_inline_nested_struct_numeric_fields_translates_to_cobol_and_executes(void);
int test_cblc_inline_function_return_used_in_expression_translates_to_cobol_and_executes(void);
int test_cblc_inline_address_of_array_element_translates_to_cobol_and_executes(void);
int test_cblc_inline_address_of_struct_field_translates_to_cobol_and_executes(void);
int test_cblc_inline_typed_pointer_null_assignment_translates_to_cobol_and_executes(void);
int test_cblc_inline_local_pointer_allocation_translates_to_cobol_and_executes(void);
int test_cblc_inline_char_pointer_variable_subtraction_translates_to_cobol_and_executes(void);
int test_cblc_inline_empty_string_literal_constructor_len_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_assignment_overwrite_len_translates_to_cobol_and_executes(void);
int test_cblc_inline_parameterized_function_return_expression_translates_to_cobol_and_executes(void);
int test_cblc_inline_nested_struct_string_overwrite_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_string_array_assign_display_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_string_array_len_after_overwrite_translates_to_cobol_and_executes(void);
int test_cblc_inline_nested_struct_string_array_translates_to_cobol_and_executes(void);
int test_cblc_inline_class_constructor_string_array_member_translates_to_cobol_and_executes(void);
int test_cblc_inline_top_level_string_array_assign_display_translates_to_cobol_and_executes(void);
int test_cblc_inline_top_level_string_array_variable_index_translates_to_cobol_and_executes(void);
int test_cblc_inline_top_level_string_array_len_after_growth_translates_to_cobol_and_executes(void);
int test_cblc_inline_top_level_string_array_append_literal_translates_to_cobol_and_executes(void);
int test_cblc_inline_top_level_string_array_clear_empty_translates_to_cobol_and_executes(void);
int test_cblc_inline_top_level_string_array_compare_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_string_array_variable_index_translates_to_cobol_and_executes(void);
int test_cblc_inline_class_method_updates_string_array_slot_translates_to_cobol_and_executes(void);
int test_cblc_inline_class_method_string_array_len_translates_to_cobol_and_executes(void);
int test_cblc_inline_nested_class_struct_string_array_append_translates_to_cobol_and_executes(void);
int test_cblc_inline_top_level_string_array_append_other_slot_translates_to_cobol_and_executes(void);
int test_cblc_inline_top_level_string_array_contains_literal_translates_to_cobol_and_executes(void);
int test_cblc_inline_top_level_string_array_starts_with_literal_translates_to_cobol_and_executes(void);
int test_cblc_inline_top_level_string_array_ends_with_literal_translates_to_cobol_and_executes(void);
int test_cblc_inline_top_level_string_array_empty_unassigned_slot_translates_to_cobol_and_executes(void);
int test_cblc_inline_top_level_string_array_clear_then_assign_translates_to_cobol_and_executes(void);
int test_cblc_inline_top_level_string_array_variable_index_append_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_string_array_append_other_slot_translates_to_cobol_and_executes(void);
int test_cblc_inline_class_method_string_array_contains_translates_to_cobol_and_executes(void);
int test_cblc_inline_nested_struct_string_array_variable_index_len_translates_to_cobol_and_executes(void);
int test_cblc_inline_local_class_instance_translates_to_cobol_and_executes(void);
int test_cblc_inline_pointer_alias_after_arithmetic_translates_to_cobol_and_executes(void);
int test_cblc_inline_pointer_reassign_between_scalars_translates_to_cobol_and_executes(void);
int test_cblc_inline_void_pointer_round_trip_char_translates_to_cobol_and_executes(void);
int test_cblc_inline_address_of_nested_struct_field_translates_to_cobol_and_executes(void);
int test_cblc_inline_address_of_array_variable_index_translates_to_cobol_and_executes(void);
int test_cblc_inline_local_void_pointer_round_trip_translates_to_cobol_and_executes(void);
int test_cblc_inline_std_strlen_symbols_literal_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_capacity_after_assignment_translates_to_cobol_and_executes(void);
int test_cblc_inline_class_string_member_update_translates_to_cobol_and_executes(void);
int test_cblc_inline_class_method_argument_multiplication_translates_to_cobol_and_executes(void);
int test_cblc_inline_pointer_argument_reads_scalar_translates_to_cobol_and_executes(void);
int test_cblc_inline_char_pointer_argument_reads_scalar_translates_to_cobol_and_executes(void);
int test_cblc_inline_pointer_argument_reads_allocated_offset_translates_to_cobol_and_executes(void);
int test_cblc_inline_global_array_pointer_parameter_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_assignment_chain_len_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_append_literal_result_translates_to_cobol_and_executes(void);
int test_cblc_inline_class_method_uses_string_len_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_string_len_translates_to_cobol_and_executes(void);
int test_cblc_inline_function_updates_global_array_translates_to_cobol_and_executes(void);
int test_cblc_inline_class_method_updates_struct_member_translates_to_cobol_and_executes(void);
int test_cblc_inline_void_pointer_parameter_reads_int_translates_to_cobol_and_executes(void);
int test_cblc_inline_pointer_parameter_reads_second_array_item_translates_to_cobol_and_executes(void);
int test_cblc_inline_pointer_parameter_updates_second_array_item_translates_to_cobol_and_executes(void);
int test_cblc_inline_allocated_char_pointer_offset_read_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_append_string_result_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_contains_after_append_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_clear_then_len_translates_to_cobol_and_executes(void);
int test_cblc_inline_class_string_method_chain_translates_to_cobol_and_executes(void);
int test_cblc_inline_class_method_accepts_struct_argument_translates_to_cobol_and_executes(void);
int test_cblc_inline_class_method_returns_struct_field_translates_to_cobol_and_executes(void);
int test_cblc_inline_function_returns_nested_struct_field_translates_to_cobol_and_executes(void);
int test_cblc_inline_method_returns_nested_struct_field_translates_to_cobol_and_executes(void);
int test_cblc_inline_void_pointer_parameter_updates_int_translates_to_cobol_and_executes(void);
int test_cblc_inline_allocated_void_pointer_round_trip_write_translates_to_cobol_and_executes(void);
int test_cblc_inline_pointer_offset_read_after_reassign_translates_to_cobol_and_executes(void);
int test_cblc_inline_char_array_pointer_parameter_reads_second_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_starts_with_after_append_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_ends_with_after_append_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_compare_after_clear_translates_to_cobol_and_executes(void);
int test_cblc_inline_class_method_string_contains_after_append_translates_to_cobol_and_executes(void);
int test_cblc_inline_class_method_accepts_pointer_argument_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_string_contains_literal_translates_to_cobol_and_executes(void);
int test_cblc_inline_void_pointer_parameter_updates_char_translates_to_cobol_and_executes(void);
int test_cblc_inline_pointer_function_returns_offset_translates_to_cobol_and_executes(void);
int test_cblc_inline_pointer_function_returns_allocated_offset_translates_to_cobol_and_executes(void);
int test_cblc_inline_char_pointer_function_returns_offset_translates_to_cobol_and_executes(void);
int test_cblc_inline_nested_struct_pointer_parameter_update_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_string_starts_with_literal_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_string_ends_with_literal_translates_to_cobol_and_executes(void);
int test_cblc_inline_class_method_clears_string_member_translates_to_cobol_and_executes(void);
int test_cblc_inline_class_method_compares_string_member_translates_to_cobol_and_executes(void);
int test_cblc_inline_global_array_pointer_rewrite_multiple_items_translates_to_cobol_and_executes(void);
int test_cblc_inline_char_pointer_parameter_updates_second_item_translates_to_cobol_and_executes(void);
int test_cblc_inline_allocated_int_pointer_sum_offsets_translates_to_cobol_and_executes(void);
int test_cblc_inline_allocated_char_pointer_rewrite_multiple_offsets_translates_to_cobol_and_executes(void);
int test_cblc_inline_void_pointer_reassigned_between_scalars_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_contains_after_clear_false_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_starts_with_after_overwrite_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_string_compare_literal_translates_to_cobol_and_executes(void);
int test_cblc_inline_class_method_string_starts_with_member_translates_to_cobol_and_executes(void);
int test_cblc_inline_class_method_string_ends_with_after_append_translates_to_cobol_and_executes(void);
int test_cblc_inline_class_method_updates_nested_struct_twice_translates_to_cobol_and_executes(void);
int test_cblc_inline_pointer_parameter_updates_offset_after_reassign_translates_to_cobol_and_executes(void);
int test_cblc_inline_pointer_parameter_sums_two_offsets_translates_to_cobol_and_executes(void);
int test_cblc_inline_allocated_pointer_return_then_write_translates_to_cobol_and_executes(void);
int test_cblc_inline_char_pointer_return_then_write_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_append_then_compare_literal_translates_to_cobol_and_executes(void);
int test_cblc_inline_string_overwrite_then_ends_with_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_string_append_then_len_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_string_clear_then_empty_translates_to_cobol_and_executes(void);
int test_cblc_inline_class_method_appends_string_member_twice_translates_to_cobol_and_executes(void);
int test_cblc_inline_class_method_writes_array_pointer_offset_translates_to_cobol_and_executes(void);
int test_cblc_inline_complex_class_struct_string_pointer_pipeline_translates_to_cobol_and_executes(void);
int test_cblc_inline_complex_dynamic_pointer_string_class_flow_translates_to_cobol_and_executes(void);
int test_cblc_inline_complex_dual_class_record_pointer_flow_translates_to_cobol_and_executes(void);
int test_cblc_inline_complex_allocated_buffer_report_flow_translates_to_cobol_and_executes(void);
int test_cblc_inline_sizeof_primitives_pointers_and_struct_translates_to_cobol_and_executes(void);
int test_cblc_inline_sizeof_malloc_int_buffer_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_pointer_int_field_write_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_pointer_int_field_read_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_pointer_char_field_write_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_pointer_string_field_write_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_pointer_string_field_display_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_pointer_string_field_len_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_pointer_nested_int_field_write_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_pointer_nested_char_field_read_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_pointer_nested_string_field_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_pointer_indexed_int_field_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_pointer_indexed_nested_int_field_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_pointer_indexed_string_field_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_pointer_cast_from_void_translates_to_cobol_and_executes(void);
int test_cblc_inline_void_pointer_cast_from_struct_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_pointer_cast_argument_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_pointer_deref_read_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_pointer_deref_write_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_pointer_deref_copy_between_pointers_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_pointer_indexed_whole_read_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_pointer_indexed_whole_write_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_pointer_indexed_whole_nested_string_copy_translates_to_cobol_and_executes(void);
int test_cblc_inline_int_pointer_to_pointer_write_translates_to_cobol_and_executes(void);
int test_cblc_inline_int_pointer_to_pointer_read_translates_to_cobol_and_executes(void);
int test_cblc_inline_int_pointer_to_pointer_retargets_pointer_translates_to_cobol_and_executes(void);
int test_cblc_inline_class_methods_translates_to_cobol_and_executes(void);
int test_cblc_inline_array_access_translates_to_cobol_and_executes(void);
int test_cblc_inline_functions_without_keyword_translates_to_cobol_and_executes(void);
int test_cblc_inline_const_values_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_field_access_translates_to_cobol_and_executes(void);
int test_cblc_inline_nested_struct_field_access_translates_to_cobol_and_executes(void);
int test_cblc_inline_variable_index_array_access_translates_to_cobol_and_executes(void);
int test_cblc_inline_constructor_initializer_translates_to_cobol_and_executes(void);
int test_cblc_inline_parameterized_class_lifecycle_translates_to_cobol_and_executes(void);
int test_cblc_inline_constructor_overloads_translates_to_cobol_and_executes(void);
int test_cblc_inline_copy_constructor_overload_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_return_translates_to_cobol_and_executes(void);
int test_cblc_inline_class_return_translates_to_cobol_and_executes(void);
int test_cblc_inline_struct_returning_method_translates_to_cobol_and_executes(void);
int test_cblc_filter_prefix_translates_to_cobol_and_executes(void);
int test_cblc_reverse_control_flow_translates_to_cobol_and_executes(void);
int test_cblc_integration_showcase_translates_to_cobol_and_executes(void);
int test_cblc_message_showcase_translates_to_cobol_and_executes(void);
int test_message_showcase_sample_make_pipeline(void);
int test_cblc_multi_module_translates_to_cobol_and_executes(void);
int test_cblc_multi_module_parameterized_call_translates_to_cobol_and_executes(void);
int test_cblc_multi_module_return_call_translates_to_cobol_and_executes(void);
int test_cblc_multi_module_parameterized_two_variables_translates_to_cobol_and_executes(void);
int test_cblc_multi_module_parameterized_literal_and_variable_translates_to_cobol_and_executes(void);
int test_cblc_multi_module_parameterized_return_two_args_translates_to_cobol_and_executes(void);
int test_cblc_multi_module_parameterized_return_literal_arg_translates_to_cobol_and_executes(void);
int test_cblc_multi_module_parameterized_three_arg_expression_translates_to_cobol_and_executes(void);
int test_cblc_multi_module_parameterized_bool_argument_translates_to_cobol_and_executes(void);
int test_cblc_multi_module_parameterized_char_argument_translates_to_cobol_and_executes(void);
int test_cblc_multi_module_parameterized_bool_return_translates_to_cobol_and_executes(void);
int test_cblc_multi_module_parameterized_char_return_translates_to_cobol_and_executes(void);
int test_cblc_multi_module_parameterized_condition_uses_arg_translates_to_cobol_and_executes(void);
int test_cblc_multi_module_parameterized_mutates_int_argument_translates_to_cobol_and_executes(void);
int test_cblc_multi_module_parameterized_mutates_two_int_arguments_translates_to_cobol_and_executes(void);
int test_cblc_multi_module_parameterized_mutates_bool_argument_translates_to_cobol_and_executes(void);
int test_cblc_multi_module_parameterized_mutates_char_argument_translates_to_cobol_and_executes(void);
int test_cblc_multi_module_parameterized_return_after_mutation_translates_to_cobol_and_executes(void);
int test_cblc_multi_module_parameterized_repeated_calls_mutate_distinct_args_translates_to_cobol_and_executes(void);
int test_cblc_multi_module_parameterized_two_literals_translates_to_cobol_and_executes(void);
int test_cblc_multi_module_parameterized_return_variable_and_literal_translates_to_cobol_and_executes(void);
int test_cblc_multi_module_parameterized_bool_return_false_branch_translates_to_cobol_and_executes(void);
int test_cblc_multi_module_parameterized_condition_after_mutation_translates_to_cobol_and_executes(void);
int test_cblc_numeric_precision_translates_to_cobol_and_executes(void);
int test_cblc_floating_point_mix_translates_to_cobol_and_executes(void);
int test_cblc_mixed_numeric_types_translates_to_cobol_and_executes(void);
int test_cblc_textual_priority_mix_translates_to_cobol_and_executes(void);
int test_cblc_reverse_group_items_translates_to_cobol_and_executes(void);
int test_cblc_return_boolean_translates_to_cobol_and_executes(void);
int test_cblc_return_character_translates_to_cobol_and_executes(void);
int test_cblc_return_numeric_translates_to_cobol_and_executes(void);
int test_cobol_reverse_control_flow_round_trips_and_executes(void);
int test_cobol_copy_file_round_trips_and_executes(void);
int test_cobol_filter_prefix_round_trips_and_executes(void);
int test_cobol_integration_showcase_round_trips_and_executes(void);
int test_cobol_multi_module_round_trips_and_executes(void);
int test_cobol_numeric_precision_round_trips_and_executes(void);
int test_cobol_floating_point_mix_round_trips_and_executes(void);
int test_cobol_mixed_numeric_types_round_trips_and_executes(void);
int test_cobol_textual_priority_mix_round_trips_and_executes(void);
int test_cobol_reverse_group_items_round_trips_and_executes(void);
int test_cobol_return_boolean_round_trips_and_executes(void);
int test_cobol_return_character_round_trips_and_executes(void);
int test_cobol_return_numeric_round_trips_and_executes(void);

const t_test_case *get_compiler_cobol_round_trip_pipeline_tests(size_t *count)
{
    static const t_test_case tests[] = {
        {"cblc_copy_file_translates_to_cobol_and_executes",
            test_cblc_copy_file_translates_to_cobol_and_executes},
        {"cblc_inline_string_append_translates_to_cobol_and_executes",
            test_cblc_inline_string_append_translates_to_cobol_and_executes},
        {"cblc_inline_string_len_translates_to_cobol_and_executes",
            test_cblc_inline_string_len_translates_to_cobol_and_executes},
        {"cblc_inline_string_clear_translates_to_cobol_and_executes",
            test_cblc_inline_string_clear_translates_to_cobol_and_executes},
        {"cblc_inline_string_empty_translates_to_cobol_and_executes",
            test_cblc_inline_string_empty_translates_to_cobol_and_executes},
        {"cblc_inline_string_equals_translates_to_cobol_and_executes",
            test_cblc_inline_string_equals_translates_to_cobol_and_executes},
        {"cblc_inline_string_equals_literal_translates_to_cobol_and_executes",
            test_cblc_inline_string_equals_literal_translates_to_cobol_and_executes},
        {"cblc_inline_string_capacity_translates_to_cobol_and_executes",
            test_cblc_inline_string_capacity_translates_to_cobol_and_executes},
        {"cblc_inline_string_starts_with_translates_to_cobol_and_executes",
            test_cblc_inline_string_starts_with_translates_to_cobol_and_executes},
        {"cblc_inline_string_ends_with_translates_to_cobol_and_executes",
            test_cblc_inline_string_ends_with_translates_to_cobol_and_executes},
        {"cblc_inline_string_compare_translates_to_cobol_and_executes",
            test_cblc_inline_string_compare_translates_to_cobol_and_executes},
        {"cblc_inline_string_contains_translates_to_cobol_and_executes",
            test_cblc_inline_string_contains_translates_to_cobol_and_executes},
        {"cblc_inline_string_equals_false_translates_to_cobol_and_executes",
            test_cblc_inline_string_equals_false_translates_to_cobol_and_executes},
        {"cblc_inline_string_empty_false_translates_to_cobol_and_executes",
            test_cblc_inline_string_empty_false_translates_to_cobol_and_executes},
        {"cblc_inline_string_starts_with_literal_translates_to_cobol_and_executes",
            test_cblc_inline_string_starts_with_literal_translates_to_cobol_and_executes},
        {"cblc_inline_string_ends_with_literal_translates_to_cobol_and_executes",
            test_cblc_inline_string_ends_with_literal_translates_to_cobol_and_executes},
        {"cblc_inline_string_compare_less_than_translates_to_cobol_and_executes",
            test_cblc_inline_string_compare_less_than_translates_to_cobol_and_executes},
        {"cblc_inline_string_compare_greater_than_translates_to_cobol_and_executes",
            test_cblc_inline_string_compare_greater_than_translates_to_cobol_and_executes},
        {"cblc_inline_string_compare_literal_translates_to_cobol_and_executes",
            test_cblc_inline_string_compare_literal_translates_to_cobol_and_executes},
        {"cblc_inline_string_contains_false_translates_to_cobol_and_executes",
            test_cblc_inline_string_contains_false_translates_to_cobol_and_executes},
        {"cblc_inline_string_contains_empty_literal_translates_to_cobol_and_executes",
            test_cblc_inline_string_contains_empty_literal_translates_to_cobol_and_executes},
        {"cblc_inline_string_constructor_capacity_translates_to_cobol_and_executes",
            test_cblc_inline_string_constructor_capacity_translates_to_cobol_and_executes},
        {"cblc_inline_string_capacity_constructor_grows_for_assignment_translates_to_cobol_and_executes",
            test_cblc_inline_string_capacity_constructor_grows_for_assignment_translates_to_cobol_and_executes},
        {"cblc_inline_string_capacity_constructor_grows_for_append_translates_to_cobol_and_executes",
            test_cblc_inline_string_capacity_constructor_grows_for_append_translates_to_cobol_and_executes},
        {"cblc_inline_string_append_then_len_translates_to_cobol_and_executes",
            test_cblc_inline_string_append_then_len_translates_to_cobol_and_executes},
        {"cblc_inline_string_clear_then_empty_translates_to_cobol_and_executes",
            test_cblc_inline_string_clear_then_empty_translates_to_cobol_and_executes},
        {"cblc_inline_string_starts_with_false_translates_to_cobol_and_executes",
            test_cblc_inline_string_starts_with_false_translates_to_cobol_and_executes},
        {"cblc_inline_string_ends_with_false_translates_to_cobol_and_executes",
            test_cblc_inline_string_ends_with_false_translates_to_cobol_and_executes},
        {"cblc_inline_string_starts_with_empty_literal_translates_to_cobol_and_executes",
            test_cblc_inline_string_starts_with_empty_literal_translates_to_cobol_and_executes},
        {"cblc_inline_string_ends_with_empty_literal_translates_to_cobol_and_executes",
            test_cblc_inline_string_ends_with_empty_literal_translates_to_cobol_and_executes},
        {"cblc_inline_string_compare_shorter_prefix_translates_to_cobol_and_executes",
            test_cblc_inline_string_compare_shorter_prefix_translates_to_cobol_and_executes},
        {"cblc_inline_string_compare_longer_prefix_translates_to_cobol_and_executes",
            test_cblc_inline_string_compare_longer_prefix_translates_to_cobol_and_executes},
        {"cblc_inline_string_contains_literal_false_translates_to_cobol_and_executes",
            test_cblc_inline_string_contains_literal_false_translates_to_cobol_and_executes},
        {"cblc_inline_string_copy_constructor_equals_translates_to_cobol_and_executes",
            test_cblc_inline_string_copy_constructor_equals_translates_to_cobol_and_executes},
        {"cblc_inline_string_literal_constructor_translates_to_cobol_and_executes",
            test_cblc_inline_string_literal_constructor_translates_to_cobol_and_executes},
        {"cblc_inline_string_copy_constructor_translates_to_cobol_and_executes",
            test_cblc_inline_string_copy_constructor_translates_to_cobol_and_executes},
        {"cblc_inline_void_pointer_alloc_free_translates_to_cobol_and_executes",
            test_cblc_inline_void_pointer_alloc_free_translates_to_cobol_and_executes},
        {"cblc_inline_int_pointer_index_translates_to_cobol_and_executes",
            test_cblc_inline_int_pointer_index_translates_to_cobol_and_executes},
        {"cblc_inline_char_pointer_index_translates_to_cobol_and_executes",
            test_cblc_inline_char_pointer_index_translates_to_cobol_and_executes},
        {"cblc_inline_pointer_arithmetic_translates_to_cobol_and_executes",
            test_cblc_inline_pointer_arithmetic_translates_to_cobol_and_executes},
        {"cblc_inline_address_of_scalar_translates_to_cobol_and_executes",
            test_cblc_inline_address_of_scalar_translates_to_cobol_and_executes},
        {"cblc_inline_pointer_return_translates_to_cobol_and_executes",
            test_cblc_inline_pointer_return_translates_to_cobol_and_executes},
        {"cblc_inline_void_pointer_to_int_pointer_translates_to_cobol_and_executes",
            test_cblc_inline_void_pointer_to_int_pointer_translates_to_cobol_and_executes},
        {"cblc_inline_int_pointer_to_void_pointer_translates_to_cobol_and_executes",
            test_cblc_inline_int_pointer_to_void_pointer_translates_to_cobol_and_executes},
        {"cblc_inline_pointer_subtraction_translates_to_cobol_and_executes",
            test_cblc_inline_pointer_subtraction_translates_to_cobol_and_executes},
        {"cblc_inline_pointer_variable_offset_translates_to_cobol_and_executes",
            test_cblc_inline_pointer_variable_offset_translates_to_cobol_and_executes},
        {"cblc_inline_char_pointer_dereference_translates_to_cobol_and_executes",
            test_cblc_inline_char_pointer_dereference_translates_to_cobol_and_executes},
        {"cblc_inline_address_of_char_scalar_translates_to_cobol_and_executes",
            test_cblc_inline_address_of_char_scalar_translates_to_cobol_and_executes},
        {"cblc_inline_local_pointer_declaration_translates_to_cobol_and_executes",
            test_cblc_inline_local_pointer_declaration_translates_to_cobol_and_executes},
        {"cblc_inline_pointer_parameter_return_translates_to_cobol_and_executes",
            test_cblc_inline_pointer_parameter_return_translates_to_cobol_and_executes},
        {"cblc_inline_realloc_pointer_translates_to_cobol_and_executes",
            test_cblc_inline_realloc_pointer_translates_to_cobol_and_executes},
        {"cblc_inline_null_pointer_assignment_translates_to_cobol_and_executes",
            test_cblc_inline_null_pointer_assignment_translates_to_cobol_and_executes},
        {"cblc_inline_pointer_offset_write_translates_to_cobol_and_executes",
            test_cblc_inline_pointer_offset_write_translates_to_cobol_and_executes},
        {"cblc_inline_pointer_argument_mutates_scalar_translates_to_cobol_and_executes",
            test_cblc_inline_pointer_argument_mutates_scalar_translates_to_cobol_and_executes},
        {"cblc_inline_pointer_argument_returns_same_pointer_translates_to_cobol_and_executes",
            test_cblc_inline_pointer_argument_returns_same_pointer_translates_to_cobol_and_executes},
        {"cblc_inline_char_pointer_arithmetic_translates_to_cobol_and_executes",
            test_cblc_inline_char_pointer_arithmetic_translates_to_cobol_and_executes},
        {"cblc_inline_char_pointer_return_translates_to_cobol_and_executes",
            test_cblc_inline_char_pointer_return_translates_to_cobol_and_executes},
        {"cblc_inline_void_pointer_address_of_int_translates_to_cobol_and_executes",
            test_cblc_inline_void_pointer_address_of_int_translates_to_cobol_and_executes},
        {"cblc_inline_realloc_int_pointer_writes_after_resize_translates_to_cobol_and_executes",
            test_cblc_inline_realloc_int_pointer_writes_after_resize_translates_to_cobol_and_executes},
        {"cblc_inline_pointer_null_after_free_translates_to_cobol_and_executes",
            test_cblc_inline_pointer_null_after_free_translates_to_cobol_and_executes},
        {"cblc_inline_std_strlen_empty_literal_translates_to_cobol_and_executes",
            test_cblc_inline_std_strlen_empty_literal_translates_to_cobol_and_executes},
        {"cblc_inline_std_strlen_spaces_literal_translates_to_cobol_and_executes",
            test_cblc_inline_std_strlen_spaces_literal_translates_to_cobol_and_executes},
        {"cblc_inline_std_strlen_literal_translates_to_cobol_and_executes",
            test_cblc_inline_std_strlen_literal_translates_to_cobol_and_executes},
        {"cblc_inline_pointer_argument_mutates_allocated_element_translates_to_cobol_and_executes",
            test_cblc_inline_pointer_argument_mutates_allocated_element_translates_to_cobol_and_executes},
        {"cblc_inline_char_pointer_argument_mutates_scalar_translates_to_cobol_and_executes",
            test_cblc_inline_char_pointer_argument_mutates_scalar_translates_to_cobol_and_executes},
        {"cblc_inline_pointer_variable_subtraction_translates_to_cobol_and_executes",
            test_cblc_inline_pointer_variable_subtraction_translates_to_cobol_and_executes},
        {"cblc_inline_local_char_pointer_declaration_translates_to_cobol_and_executes",
            test_cblc_inline_local_char_pointer_declaration_translates_to_cobol_and_executes},
        {"cblc_inline_string_clear_after_assignment_translates_to_cobol_and_executes",
            test_cblc_inline_string_clear_after_assignment_translates_to_cobol_and_executes},
        {"cblc_inline_string_copy_constructor_len_translates_to_cobol_and_executes",
            test_cblc_inline_string_copy_constructor_len_translates_to_cobol_and_executes},
        {"cblc_inline_class_multiple_method_calls_translates_to_cobol_and_executes",
            test_cblc_inline_class_multiple_method_calls_translates_to_cobol_and_executes},
        {"cblc_inline_class_const_member_arithmetic_translates_to_cobol_and_executes",
            test_cblc_inline_class_const_member_arithmetic_translates_to_cobol_and_executes},
        {"cblc_inline_nested_struct_numeric_fields_translates_to_cobol_and_executes",
            test_cblc_inline_nested_struct_numeric_fields_translates_to_cobol_and_executes},
        {"cblc_inline_function_return_used_in_expression_translates_to_cobol_and_executes",
            test_cblc_inline_function_return_used_in_expression_translates_to_cobol_and_executes},
        {"cblc_inline_address_of_array_element_translates_to_cobol_and_executes",
            test_cblc_inline_address_of_array_element_translates_to_cobol_and_executes},
        {"cblc_inline_address_of_struct_field_translates_to_cobol_and_executes",
            test_cblc_inline_address_of_struct_field_translates_to_cobol_and_executes},
        {"cblc_inline_typed_pointer_null_assignment_translates_to_cobol_and_executes",
            test_cblc_inline_typed_pointer_null_assignment_translates_to_cobol_and_executes},
        {"cblc_inline_local_pointer_allocation_translates_to_cobol_and_executes",
            test_cblc_inline_local_pointer_allocation_translates_to_cobol_and_executes},
        {"cblc_inline_char_pointer_variable_subtraction_translates_to_cobol_and_executes",
            test_cblc_inline_char_pointer_variable_subtraction_translates_to_cobol_and_executes},
        {"cblc_inline_empty_string_literal_constructor_len_translates_to_cobol_and_executes",
            test_cblc_inline_empty_string_literal_constructor_len_translates_to_cobol_and_executes},
        {"cblc_inline_string_assignment_overwrite_len_translates_to_cobol_and_executes",
            test_cblc_inline_string_assignment_overwrite_len_translates_to_cobol_and_executes},
        {"cblc_inline_parameterized_function_return_expression_translates_to_cobol_and_executes",
            test_cblc_inline_parameterized_function_return_expression_translates_to_cobol_and_executes},
        {"cblc_inline_nested_struct_string_overwrite_translates_to_cobol_and_executes",
            test_cblc_inline_nested_struct_string_overwrite_translates_to_cobol_and_executes},
        {"cblc_inline_struct_string_array_assign_display_translates_to_cobol_and_executes",
            test_cblc_inline_struct_string_array_assign_display_translates_to_cobol_and_executes},
        {"cblc_inline_struct_string_array_len_after_overwrite_translates_to_cobol_and_executes",
            test_cblc_inline_struct_string_array_len_after_overwrite_translates_to_cobol_and_executes},
        {"cblc_inline_nested_struct_string_array_translates_to_cobol_and_executes",
            test_cblc_inline_nested_struct_string_array_translates_to_cobol_and_executes},
        {"cblc_inline_class_constructor_string_array_member_translates_to_cobol_and_executes",
            test_cblc_inline_class_constructor_string_array_member_translates_to_cobol_and_executes},
        {"cblc_inline_top_level_string_array_assign_display_translates_to_cobol_and_executes",
            test_cblc_inline_top_level_string_array_assign_display_translates_to_cobol_and_executes},
        {"cblc_inline_top_level_string_array_variable_index_translates_to_cobol_and_executes",
            test_cblc_inline_top_level_string_array_variable_index_translates_to_cobol_and_executes},
        {"cblc_inline_top_level_string_array_len_after_growth_translates_to_cobol_and_executes",
            test_cblc_inline_top_level_string_array_len_after_growth_translates_to_cobol_and_executes},
        {"cblc_inline_top_level_string_array_append_literal_translates_to_cobol_and_executes",
            test_cblc_inline_top_level_string_array_append_literal_translates_to_cobol_and_executes},
        {"cblc_inline_top_level_string_array_clear_empty_translates_to_cobol_and_executes",
            test_cblc_inline_top_level_string_array_clear_empty_translates_to_cobol_and_executes},
        {"cblc_inline_top_level_string_array_compare_translates_to_cobol_and_executes",
            test_cblc_inline_top_level_string_array_compare_translates_to_cobol_and_executes},
        {"cblc_inline_struct_string_array_variable_index_translates_to_cobol_and_executes",
            test_cblc_inline_struct_string_array_variable_index_translates_to_cobol_and_executes},
        {"cblc_inline_class_method_updates_string_array_slot_translates_to_cobol_and_executes",
            test_cblc_inline_class_method_updates_string_array_slot_translates_to_cobol_and_executes},
        {"cblc_inline_class_method_string_array_len_translates_to_cobol_and_executes",
            test_cblc_inline_class_method_string_array_len_translates_to_cobol_and_executes},
        {"cblc_inline_nested_class_struct_string_array_append_translates_to_cobol_and_executes",
            test_cblc_inline_nested_class_struct_string_array_append_translates_to_cobol_and_executes},
        {"cblc_inline_top_level_string_array_append_other_slot_translates_to_cobol_and_executes",
            test_cblc_inline_top_level_string_array_append_other_slot_translates_to_cobol_and_executes},
        {"cblc_inline_top_level_string_array_contains_literal_translates_to_cobol_and_executes",
            test_cblc_inline_top_level_string_array_contains_literal_translates_to_cobol_and_executes},
        {"cblc_inline_top_level_string_array_starts_with_literal_translates_to_cobol_and_executes",
            test_cblc_inline_top_level_string_array_starts_with_literal_translates_to_cobol_and_executes},
        {"cblc_inline_top_level_string_array_ends_with_literal_translates_to_cobol_and_executes",
            test_cblc_inline_top_level_string_array_ends_with_literal_translates_to_cobol_and_executes},
        {"cblc_inline_top_level_string_array_empty_unassigned_slot_translates_to_cobol_and_executes",
            test_cblc_inline_top_level_string_array_empty_unassigned_slot_translates_to_cobol_and_executes},
        {"cblc_inline_top_level_string_array_clear_then_assign_translates_to_cobol_and_executes",
            test_cblc_inline_top_level_string_array_clear_then_assign_translates_to_cobol_and_executes},
        {"cblc_inline_top_level_string_array_variable_index_append_translates_to_cobol_and_executes",
            test_cblc_inline_top_level_string_array_variable_index_append_translates_to_cobol_and_executes},
        {"cblc_inline_struct_string_array_append_other_slot_translates_to_cobol_and_executes",
            test_cblc_inline_struct_string_array_append_other_slot_translates_to_cobol_and_executes},
        {"cblc_inline_class_method_string_array_contains_translates_to_cobol_and_executes",
            test_cblc_inline_class_method_string_array_contains_translates_to_cobol_and_executes},
        {"cblc_inline_nested_struct_string_array_variable_index_len_translates_to_cobol_and_executes",
            test_cblc_inline_nested_struct_string_array_variable_index_len_translates_to_cobol_and_executes},
        {"cblc_inline_local_class_instance_translates_to_cobol_and_executes",
            test_cblc_inline_local_class_instance_translates_to_cobol_and_executes},
        {"cblc_inline_pointer_alias_after_arithmetic_translates_to_cobol_and_executes",
            test_cblc_inline_pointer_alias_after_arithmetic_translates_to_cobol_and_executes},
        {"cblc_inline_pointer_reassign_between_scalars_translates_to_cobol_and_executes",
            test_cblc_inline_pointer_reassign_between_scalars_translates_to_cobol_and_executes},
        {"cblc_inline_void_pointer_round_trip_char_translates_to_cobol_and_executes",
            test_cblc_inline_void_pointer_round_trip_char_translates_to_cobol_and_executes},
        {"cblc_inline_address_of_nested_struct_field_translates_to_cobol_and_executes",
            test_cblc_inline_address_of_nested_struct_field_translates_to_cobol_and_executes},
        {"cblc_inline_address_of_array_variable_index_translates_to_cobol_and_executes",
            test_cblc_inline_address_of_array_variable_index_translates_to_cobol_and_executes},
        {"cblc_inline_local_void_pointer_round_trip_translates_to_cobol_and_executes",
            test_cblc_inline_local_void_pointer_round_trip_translates_to_cobol_and_executes},
        {"cblc_inline_std_strlen_symbols_literal_translates_to_cobol_and_executes",
            test_cblc_inline_std_strlen_symbols_literal_translates_to_cobol_and_executes},
        {"cblc_inline_string_capacity_after_assignment_translates_to_cobol_and_executes",
            test_cblc_inline_string_capacity_after_assignment_translates_to_cobol_and_executes},
        {"cblc_inline_class_string_member_update_translates_to_cobol_and_executes",
            test_cblc_inline_class_string_member_update_translates_to_cobol_and_executes},
        {"cblc_inline_class_method_argument_multiplication_translates_to_cobol_and_executes",
            test_cblc_inline_class_method_argument_multiplication_translates_to_cobol_and_executes},
        {"cblc_inline_pointer_argument_reads_scalar_translates_to_cobol_and_executes",
            test_cblc_inline_pointer_argument_reads_scalar_translates_to_cobol_and_executes},
        {"cblc_inline_char_pointer_argument_reads_scalar_translates_to_cobol_and_executes",
            test_cblc_inline_char_pointer_argument_reads_scalar_translates_to_cobol_and_executes},
        {"cblc_inline_pointer_argument_reads_allocated_offset_translates_to_cobol_and_executes",
            test_cblc_inline_pointer_argument_reads_allocated_offset_translates_to_cobol_and_executes},
        {"cblc_inline_global_array_pointer_parameter_translates_to_cobol_and_executes",
            test_cblc_inline_global_array_pointer_parameter_translates_to_cobol_and_executes},
        {"cblc_inline_string_assignment_chain_len_translates_to_cobol_and_executes",
            test_cblc_inline_string_assignment_chain_len_translates_to_cobol_and_executes},
        {"cblc_inline_string_append_literal_result_translates_to_cobol_and_executes",
            test_cblc_inline_string_append_literal_result_translates_to_cobol_and_executes},
        {"cblc_inline_class_method_uses_string_len_translates_to_cobol_and_executes",
            test_cblc_inline_class_method_uses_string_len_translates_to_cobol_and_executes},
        {"cblc_inline_struct_string_len_translates_to_cobol_and_executes",
            test_cblc_inline_struct_string_len_translates_to_cobol_and_executes},
        {"cblc_inline_function_updates_global_array_translates_to_cobol_and_executes",
            test_cblc_inline_function_updates_global_array_translates_to_cobol_and_executes},
        {"cblc_inline_class_method_updates_struct_member_translates_to_cobol_and_executes",
            test_cblc_inline_class_method_updates_struct_member_translates_to_cobol_and_executes},
        {"cblc_inline_void_pointer_parameter_reads_int_translates_to_cobol_and_executes",
            test_cblc_inline_void_pointer_parameter_reads_int_translates_to_cobol_and_executes},
        {"cblc_inline_pointer_parameter_reads_second_array_item_translates_to_cobol_and_executes",
            test_cblc_inline_pointer_parameter_reads_second_array_item_translates_to_cobol_and_executes},
        {"cblc_inline_pointer_parameter_updates_second_array_item_translates_to_cobol_and_executes",
            test_cblc_inline_pointer_parameter_updates_second_array_item_translates_to_cobol_and_executes},
        {"cblc_inline_allocated_char_pointer_offset_read_translates_to_cobol_and_executes",
            test_cblc_inline_allocated_char_pointer_offset_read_translates_to_cobol_and_executes},
        {"cblc_inline_string_append_string_result_translates_to_cobol_and_executes",
            test_cblc_inline_string_append_string_result_translates_to_cobol_and_executes},
        {"cblc_inline_string_contains_after_append_translates_to_cobol_and_executes",
            test_cblc_inline_string_contains_after_append_translates_to_cobol_and_executes},
        {"cblc_inline_string_clear_then_len_translates_to_cobol_and_executes",
            test_cblc_inline_string_clear_then_len_translates_to_cobol_and_executes},
        {"cblc_inline_class_string_method_chain_translates_to_cobol_and_executes",
            test_cblc_inline_class_string_method_chain_translates_to_cobol_and_executes},
        {"cblc_inline_class_method_accepts_struct_argument_translates_to_cobol_and_executes",
            test_cblc_inline_class_method_accepts_struct_argument_translates_to_cobol_and_executes},
        {"cblc_inline_class_method_returns_struct_field_translates_to_cobol_and_executes",
            test_cblc_inline_class_method_returns_struct_field_translates_to_cobol_and_executes},
        {"cblc_inline_function_returns_nested_struct_field_translates_to_cobol_and_executes",
            test_cblc_inline_function_returns_nested_struct_field_translates_to_cobol_and_executes},
        {"cblc_inline_method_returns_nested_struct_field_translates_to_cobol_and_executes",
            test_cblc_inline_method_returns_nested_struct_field_translates_to_cobol_and_executes},
        {"cblc_inline_void_pointer_parameter_updates_int_translates_to_cobol_and_executes",
            test_cblc_inline_void_pointer_parameter_updates_int_translates_to_cobol_and_executes},
        {"cblc_inline_allocated_void_pointer_round_trip_write_translates_to_cobol_and_executes",
            test_cblc_inline_allocated_void_pointer_round_trip_write_translates_to_cobol_and_executes},
        {"cblc_inline_pointer_offset_read_after_reassign_translates_to_cobol_and_executes",
            test_cblc_inline_pointer_offset_read_after_reassign_translates_to_cobol_and_executes},
        {"cblc_inline_char_array_pointer_parameter_reads_second_translates_to_cobol_and_executes",
            test_cblc_inline_char_array_pointer_parameter_reads_second_translates_to_cobol_and_executes},
        {"cblc_inline_string_starts_with_after_append_translates_to_cobol_and_executes",
            test_cblc_inline_string_starts_with_after_append_translates_to_cobol_and_executes},
        {"cblc_inline_string_ends_with_after_append_translates_to_cobol_and_executes",
            test_cblc_inline_string_ends_with_after_append_translates_to_cobol_and_executes},
        {"cblc_inline_string_compare_after_clear_translates_to_cobol_and_executes",
            test_cblc_inline_string_compare_after_clear_translates_to_cobol_and_executes},
        {"cblc_inline_class_method_string_contains_after_append_translates_to_cobol_and_executes",
            test_cblc_inline_class_method_string_contains_after_append_translates_to_cobol_and_executes},
        {"cblc_inline_class_method_accepts_pointer_argument_translates_to_cobol_and_executes",
            test_cblc_inline_class_method_accepts_pointer_argument_translates_to_cobol_and_executes},
        {"cblc_inline_struct_string_contains_literal_translates_to_cobol_and_executes",
            test_cblc_inline_struct_string_contains_literal_translates_to_cobol_and_executes},
        {"cblc_inline_void_pointer_parameter_updates_char_translates_to_cobol_and_executes",
            test_cblc_inline_void_pointer_parameter_updates_char_translates_to_cobol_and_executes},
        {"cblc_inline_pointer_function_returns_offset_translates_to_cobol_and_executes",
            test_cblc_inline_pointer_function_returns_offset_translates_to_cobol_and_executes},
        {"cblc_inline_pointer_function_returns_allocated_offset_translates_to_cobol_and_executes",
            test_cblc_inline_pointer_function_returns_allocated_offset_translates_to_cobol_and_executes},
        {"cblc_inline_char_pointer_function_returns_offset_translates_to_cobol_and_executes",
            test_cblc_inline_char_pointer_function_returns_offset_translates_to_cobol_and_executes},
        {"cblc_inline_nested_struct_pointer_parameter_update_translates_to_cobol_and_executes",
            test_cblc_inline_nested_struct_pointer_parameter_update_translates_to_cobol_and_executes},
        {"cblc_inline_struct_string_starts_with_literal_translates_to_cobol_and_executes",
            test_cblc_inline_struct_string_starts_with_literal_translates_to_cobol_and_executes},
        {"cblc_inline_struct_string_ends_with_literal_translates_to_cobol_and_executes",
            test_cblc_inline_struct_string_ends_with_literal_translates_to_cobol_and_executes},
        {"cblc_inline_class_method_clears_string_member_translates_to_cobol_and_executes",
            test_cblc_inline_class_method_clears_string_member_translates_to_cobol_and_executes},
        {"cblc_inline_class_method_compares_string_member_translates_to_cobol_and_executes",
            test_cblc_inline_class_method_compares_string_member_translates_to_cobol_and_executes},
        {"cblc_inline_global_array_pointer_rewrite_multiple_items_translates_to_cobol_and_executes",
            test_cblc_inline_global_array_pointer_rewrite_multiple_items_translates_to_cobol_and_executes},
        {"cblc_inline_char_pointer_parameter_updates_second_item_translates_to_cobol_and_executes",
            test_cblc_inline_char_pointer_parameter_updates_second_item_translates_to_cobol_and_executes},
        {"cblc_inline_allocated_int_pointer_sum_offsets_translates_to_cobol_and_executes",
            test_cblc_inline_allocated_int_pointer_sum_offsets_translates_to_cobol_and_executes},
        {"cblc_inline_allocated_char_pointer_rewrite_multiple_offsets_translates_to_cobol_and_executes",
            test_cblc_inline_allocated_char_pointer_rewrite_multiple_offsets_translates_to_cobol_and_executes},
        {"cblc_inline_void_pointer_reassigned_between_scalars_translates_to_cobol_and_executes",
            test_cblc_inline_void_pointer_reassigned_between_scalars_translates_to_cobol_and_executes},
        {"cblc_inline_string_contains_after_clear_false_translates_to_cobol_and_executes",
            test_cblc_inline_string_contains_after_clear_false_translates_to_cobol_and_executes},
        {"cblc_inline_string_starts_with_after_overwrite_translates_to_cobol_and_executes",
            test_cblc_inline_string_starts_with_after_overwrite_translates_to_cobol_and_executes},
        {"cblc_inline_struct_string_compare_literal_translates_to_cobol_and_executes",
            test_cblc_inline_struct_string_compare_literal_translates_to_cobol_and_executes},
        {"cblc_inline_class_method_string_starts_with_member_translates_to_cobol_and_executes",
            test_cblc_inline_class_method_string_starts_with_member_translates_to_cobol_and_executes},
        {"cblc_inline_class_method_string_ends_with_after_append_translates_to_cobol_and_executes",
            test_cblc_inline_class_method_string_ends_with_after_append_translates_to_cobol_and_executes},
        {"cblc_inline_class_method_updates_nested_struct_twice_translates_to_cobol_and_executes",
            test_cblc_inline_class_method_updates_nested_struct_twice_translates_to_cobol_and_executes},
        {"cblc_inline_pointer_parameter_updates_offset_after_reassign_translates_to_cobol_and_executes",
            test_cblc_inline_pointer_parameter_updates_offset_after_reassign_translates_to_cobol_and_executes},
        {"cblc_inline_pointer_parameter_sums_two_offsets_translates_to_cobol_and_executes",
            test_cblc_inline_pointer_parameter_sums_two_offsets_translates_to_cobol_and_executes},
        {"cblc_inline_allocated_pointer_return_then_write_translates_to_cobol_and_executes",
            test_cblc_inline_allocated_pointer_return_then_write_translates_to_cobol_and_executes},
        {"cblc_inline_char_pointer_return_then_write_translates_to_cobol_and_executes",
            test_cblc_inline_char_pointer_return_then_write_translates_to_cobol_and_executes},
        {"cblc_inline_string_append_then_compare_literal_translates_to_cobol_and_executes",
            test_cblc_inline_string_append_then_compare_literal_translates_to_cobol_and_executes},
        {"cblc_inline_string_overwrite_then_ends_with_translates_to_cobol_and_executes",
            test_cblc_inline_string_overwrite_then_ends_with_translates_to_cobol_and_executes},
        {"cblc_inline_struct_string_append_then_len_translates_to_cobol_and_executes",
            test_cblc_inline_struct_string_append_then_len_translates_to_cobol_and_executes},
        {"cblc_inline_struct_string_clear_then_empty_translates_to_cobol_and_executes",
            test_cblc_inline_struct_string_clear_then_empty_translates_to_cobol_and_executes},
        {"cblc_inline_class_method_appends_string_member_twice_translates_to_cobol_and_executes",
            test_cblc_inline_class_method_appends_string_member_twice_translates_to_cobol_and_executes},
        {"cblc_inline_class_method_writes_array_pointer_offset_translates_to_cobol_and_executes",
            test_cblc_inline_class_method_writes_array_pointer_offset_translates_to_cobol_and_executes},
        {"cblc_inline_complex_class_struct_string_pointer_pipeline_translates_to_cobol_and_executes",
            test_cblc_inline_complex_class_struct_string_pointer_pipeline_translates_to_cobol_and_executes},
        {"cblc_inline_complex_dynamic_pointer_string_class_flow_translates_to_cobol_and_executes",
            test_cblc_inline_complex_dynamic_pointer_string_class_flow_translates_to_cobol_and_executes},
        {"cblc_inline_complex_dual_class_record_pointer_flow_translates_to_cobol_and_executes",
            test_cblc_inline_complex_dual_class_record_pointer_flow_translates_to_cobol_and_executes},
        {"cblc_inline_complex_allocated_buffer_report_flow_translates_to_cobol_and_executes",
            test_cblc_inline_complex_allocated_buffer_report_flow_translates_to_cobol_and_executes},
        {"cblc_inline_sizeof_primitives_pointers_and_struct_translates_to_cobol_and_executes",
            test_cblc_inline_sizeof_primitives_pointers_and_struct_translates_to_cobol_and_executes},
        {"cblc_inline_sizeof_malloc_int_buffer_translates_to_cobol_and_executes",
            test_cblc_inline_sizeof_malloc_int_buffer_translates_to_cobol_and_executes},
        {"cblc_inline_struct_pointer_int_field_write_translates_to_cobol_and_executes",
            test_cblc_inline_struct_pointer_int_field_write_translates_to_cobol_and_executes},
        {"cblc_inline_struct_pointer_int_field_read_translates_to_cobol_and_executes",
            test_cblc_inline_struct_pointer_int_field_read_translates_to_cobol_and_executes},
        {"cblc_inline_struct_pointer_char_field_write_translates_to_cobol_and_executes",
            test_cblc_inline_struct_pointer_char_field_write_translates_to_cobol_and_executes},
        {"cblc_inline_struct_pointer_string_field_write_translates_to_cobol_and_executes",
            test_cblc_inline_struct_pointer_string_field_write_translates_to_cobol_and_executes},
        {"cblc_inline_struct_pointer_string_field_display_translates_to_cobol_and_executes",
            test_cblc_inline_struct_pointer_string_field_display_translates_to_cobol_and_executes},
        {"cblc_inline_struct_pointer_string_field_len_translates_to_cobol_and_executes",
            test_cblc_inline_struct_pointer_string_field_len_translates_to_cobol_and_executes},
        {"cblc_inline_struct_pointer_nested_int_field_write_translates_to_cobol_and_executes",
            test_cblc_inline_struct_pointer_nested_int_field_write_translates_to_cobol_and_executes},
        {"cblc_inline_struct_pointer_nested_char_field_read_translates_to_cobol_and_executes",
            test_cblc_inline_struct_pointer_nested_char_field_read_translates_to_cobol_and_executes},
        {"cblc_inline_struct_pointer_nested_string_field_translates_to_cobol_and_executes",
            test_cblc_inline_struct_pointer_nested_string_field_translates_to_cobol_and_executes},
        {"cblc_inline_struct_pointer_indexed_int_field_translates_to_cobol_and_executes",
            test_cblc_inline_struct_pointer_indexed_int_field_translates_to_cobol_and_executes},
        {"cblc_inline_struct_pointer_indexed_nested_int_field_translates_to_cobol_and_executes",
            test_cblc_inline_struct_pointer_indexed_nested_int_field_translates_to_cobol_and_executes},
        {"cblc_inline_struct_pointer_indexed_string_field_translates_to_cobol_and_executes",
            test_cblc_inline_struct_pointer_indexed_string_field_translates_to_cobol_and_executes},
        {"cblc_inline_struct_pointer_cast_from_void_translates_to_cobol_and_executes",
            test_cblc_inline_struct_pointer_cast_from_void_translates_to_cobol_and_executes},
        {"cblc_inline_void_pointer_cast_from_struct_translates_to_cobol_and_executes",
            test_cblc_inline_void_pointer_cast_from_struct_translates_to_cobol_and_executes},
        {"cblc_inline_struct_pointer_cast_argument_translates_to_cobol_and_executes",
            test_cblc_inline_struct_pointer_cast_argument_translates_to_cobol_and_executes},
        {"cblc_inline_struct_pointer_deref_read_translates_to_cobol_and_executes",
            test_cblc_inline_struct_pointer_deref_read_translates_to_cobol_and_executes},
        {"cblc_inline_struct_pointer_deref_write_translates_to_cobol_and_executes",
            test_cblc_inline_struct_pointer_deref_write_translates_to_cobol_and_executes},
        {"cblc_inline_struct_pointer_deref_copy_between_pointers_translates_to_cobol_and_executes",
            test_cblc_inline_struct_pointer_deref_copy_between_pointers_translates_to_cobol_and_executes},
        {"cblc_inline_struct_pointer_indexed_whole_read_translates_to_cobol_and_executes",
            test_cblc_inline_struct_pointer_indexed_whole_read_translates_to_cobol_and_executes},
        {"cblc_inline_struct_pointer_indexed_whole_write_translates_to_cobol_and_executes",
            test_cblc_inline_struct_pointer_indexed_whole_write_translates_to_cobol_and_executes},
        {"cblc_inline_struct_pointer_indexed_whole_nested_string_copy_translates_to_cobol_and_executes",
            test_cblc_inline_struct_pointer_indexed_whole_nested_string_copy_translates_to_cobol_and_executes},
        {"cblc_inline_int_pointer_to_pointer_write_translates_to_cobol_and_executes",
            test_cblc_inline_int_pointer_to_pointer_write_translates_to_cobol_and_executes},
        {"cblc_inline_int_pointer_to_pointer_read_translates_to_cobol_and_executes",
            test_cblc_inline_int_pointer_to_pointer_read_translates_to_cobol_and_executes},
        {"cblc_inline_int_pointer_to_pointer_retargets_pointer_translates_to_cobol_and_executes",
            test_cblc_inline_int_pointer_to_pointer_retargets_pointer_translates_to_cobol_and_executes},
        {"cblc_inline_class_methods_translates_to_cobol_and_executes",
            test_cblc_inline_class_methods_translates_to_cobol_and_executes},
        {"cblc_inline_array_access_translates_to_cobol_and_executes",
            test_cblc_inline_array_access_translates_to_cobol_and_executes},
        {"cblc_inline_functions_without_keyword_translates_to_cobol_and_executes",
            test_cblc_inline_functions_without_keyword_translates_to_cobol_and_executes},
        {"cblc_inline_const_values_translates_to_cobol_and_executes",
            test_cblc_inline_const_values_translates_to_cobol_and_executes},
        {"cblc_inline_struct_field_access_translates_to_cobol_and_executes",
            test_cblc_inline_struct_field_access_translates_to_cobol_and_executes},
        {"cblc_inline_nested_struct_field_access_translates_to_cobol_and_executes",
            test_cblc_inline_nested_struct_field_access_translates_to_cobol_and_executes},
        {"cblc_inline_variable_index_array_access_translates_to_cobol_and_executes",
            test_cblc_inline_variable_index_array_access_translates_to_cobol_and_executes},
        {"cblc_inline_constructor_initializer_translates_to_cobol_and_executes",
            test_cblc_inline_constructor_initializer_translates_to_cobol_and_executes},
        {"cblc_inline_parameterized_class_lifecycle_translates_to_cobol_and_executes",
            test_cblc_inline_parameterized_class_lifecycle_translates_to_cobol_and_executes},
        {"cblc_inline_constructor_overloads_translates_to_cobol_and_executes",
            test_cblc_inline_constructor_overloads_translates_to_cobol_and_executes},
        {"cblc_inline_copy_constructor_overload_translates_to_cobol_and_executes",
            test_cblc_inline_copy_constructor_overload_translates_to_cobol_and_executes},
        {"cblc_inline_struct_return_translates_to_cobol_and_executes",
            test_cblc_inline_struct_return_translates_to_cobol_and_executes},
        {"cblc_inline_class_return_translates_to_cobol_and_executes",
            test_cblc_inline_class_return_translates_to_cobol_and_executes},
        {"cblc_inline_struct_returning_method_translates_to_cobol_and_executes",
            test_cblc_inline_struct_returning_method_translates_to_cobol_and_executes},
        {"cblc_filter_prefix_translates_to_cobol_and_executes",
            test_cblc_filter_prefix_translates_to_cobol_and_executes},
        {"cblc_reverse_control_flow_translates_to_cobol_and_executes",
            test_cblc_reverse_control_flow_translates_to_cobol_and_executes},
        {"cblc_integration_showcase_translates_to_cobol_and_executes",
            test_cblc_integration_showcase_translates_to_cobol_and_executes},
        {"cblc_message_showcase_translates_to_cobol_and_executes",
            test_cblc_message_showcase_translates_to_cobol_and_executes},
        {"message_showcase_sample_make_pipeline", test_message_showcase_sample_make_pipeline},
        {"cblc_multi_module_translates_to_cobol_and_executes",
            test_cblc_multi_module_translates_to_cobol_and_executes},
        {"cblc_multi_module_parameterized_call_translates_to_cobol_and_executes",
            test_cblc_multi_module_parameterized_call_translates_to_cobol_and_executes},
        {"cblc_multi_module_return_call_translates_to_cobol_and_executes",
            test_cblc_multi_module_return_call_translates_to_cobol_and_executes},
        {"cblc_multi_module_parameterized_two_variables_translates_to_cobol_and_executes",
            test_cblc_multi_module_parameterized_two_variables_translates_to_cobol_and_executes},
        {"cblc_multi_module_parameterized_literal_and_variable_translates_to_cobol_and_executes",
            test_cblc_multi_module_parameterized_literal_and_variable_translates_to_cobol_and_executes},
        {"cblc_multi_module_parameterized_return_two_args_translates_to_cobol_and_executes",
            test_cblc_multi_module_parameterized_return_two_args_translates_to_cobol_and_executes},
        {"cblc_multi_module_parameterized_return_literal_arg_translates_to_cobol_and_executes",
            test_cblc_multi_module_parameterized_return_literal_arg_translates_to_cobol_and_executes},
        {"cblc_multi_module_parameterized_three_arg_expression_translates_to_cobol_and_executes",
            test_cblc_multi_module_parameterized_three_arg_expression_translates_to_cobol_and_executes},
        {"cblc_multi_module_parameterized_bool_argument_translates_to_cobol_and_executes",
            test_cblc_multi_module_parameterized_bool_argument_translates_to_cobol_and_executes},
        {"cblc_multi_module_parameterized_char_argument_translates_to_cobol_and_executes",
            test_cblc_multi_module_parameterized_char_argument_translates_to_cobol_and_executes},
        {"cblc_multi_module_parameterized_bool_return_translates_to_cobol_and_executes",
            test_cblc_multi_module_parameterized_bool_return_translates_to_cobol_and_executes},
        {"cblc_multi_module_parameterized_char_return_translates_to_cobol_and_executes",
            test_cblc_multi_module_parameterized_char_return_translates_to_cobol_and_executes},
        {"cblc_multi_module_parameterized_condition_uses_arg_translates_to_cobol_and_executes",
            test_cblc_multi_module_parameterized_condition_uses_arg_translates_to_cobol_and_executes},
        {"cblc_multi_module_parameterized_mutates_int_argument_translates_to_cobol_and_executes",
            test_cblc_multi_module_parameterized_mutates_int_argument_translates_to_cobol_and_executes},
        {"cblc_multi_module_parameterized_mutates_two_int_arguments_translates_to_cobol_and_executes",
            test_cblc_multi_module_parameterized_mutates_two_int_arguments_translates_to_cobol_and_executes},
        {"cblc_multi_module_parameterized_mutates_bool_argument_translates_to_cobol_and_executes",
            test_cblc_multi_module_parameterized_mutates_bool_argument_translates_to_cobol_and_executes},
        {"cblc_multi_module_parameterized_mutates_char_argument_translates_to_cobol_and_executes",
            test_cblc_multi_module_parameterized_mutates_char_argument_translates_to_cobol_and_executes},
        {"cblc_multi_module_parameterized_return_after_mutation_translates_to_cobol_and_executes",
            test_cblc_multi_module_parameterized_return_after_mutation_translates_to_cobol_and_executes},
        {"cblc_multi_module_parameterized_repeated_calls_mutate_distinct_args_translates_to_cobol_and_executes",
            test_cblc_multi_module_parameterized_repeated_calls_mutate_distinct_args_translates_to_cobol_and_executes},
        {"cblc_multi_module_parameterized_two_literals_translates_to_cobol_and_executes",
            test_cblc_multi_module_parameterized_two_literals_translates_to_cobol_and_executes},
        {"cblc_multi_module_parameterized_return_variable_and_literal_translates_to_cobol_and_executes",
            test_cblc_multi_module_parameterized_return_variable_and_literal_translates_to_cobol_and_executes},
        {"cblc_multi_module_parameterized_bool_return_false_branch_translates_to_cobol_and_executes",
            test_cblc_multi_module_parameterized_bool_return_false_branch_translates_to_cobol_and_executes},
        {"cblc_multi_module_parameterized_condition_after_mutation_translates_to_cobol_and_executes",
            test_cblc_multi_module_parameterized_condition_after_mutation_translates_to_cobol_and_executes},
        {"cblc_numeric_precision_translates_to_cobol_and_executes",
            test_cblc_numeric_precision_translates_to_cobol_and_executes},
        {"cblc_floating_point_mix_translates_to_cobol_and_executes",
            test_cblc_floating_point_mix_translates_to_cobol_and_executes},
        {"cblc_mixed_numeric_types_translates_to_cobol_and_executes",
            test_cblc_mixed_numeric_types_translates_to_cobol_and_executes},
        {"cblc_textual_priority_mix_translates_to_cobol_and_executes",
            test_cblc_textual_priority_mix_translates_to_cobol_and_executes},
        {"cblc_reverse_group_items_translates_to_cobol_and_executes",
            test_cblc_reverse_group_items_translates_to_cobol_and_executes},
        {"cblc_return_boolean_translates_to_cobol_and_executes",
            test_cblc_return_boolean_translates_to_cobol_and_executes},
        {"cblc_return_character_translates_to_cobol_and_executes",
            test_cblc_return_character_translates_to_cobol_and_executes},
        {"cblc_return_numeric_translates_to_cobol_and_executes",
            test_cblc_return_numeric_translates_to_cobol_and_executes},
        {"cobol_reverse_control_flow_round_trips_and_executes",
            test_cobol_reverse_control_flow_round_trips_and_executes},
        {"cobol_copy_file_round_trips_and_executes",
            test_cobol_copy_file_round_trips_and_executes},
        {"cobol_filter_prefix_round_trips_and_executes",
            test_cobol_filter_prefix_round_trips_and_executes},
        {"cobol_integration_showcase_round_trips_and_executes",
            test_cobol_integration_showcase_round_trips_and_executes},
        {"cobol_multi_module_round_trips_and_executes",
            test_cobol_multi_module_round_trips_and_executes},
        {"cobol_numeric_precision_round_trips_and_executes",
            test_cobol_numeric_precision_round_trips_and_executes},
        {"cobol_floating_point_mix_round_trips_and_executes",
            test_cobol_floating_point_mix_round_trips_and_executes},
        {"cobol_mixed_numeric_types_round_trips_and_executes",
            test_cobol_mixed_numeric_types_round_trips_and_executes},
        {"cobol_textual_priority_mix_round_trips_and_executes",
            test_cobol_textual_priority_mix_round_trips_and_executes},
        {"cobol_reverse_group_items_round_trips_and_executes",
            test_cobol_reverse_group_items_round_trips_and_executes},
        {"cobol_return_boolean_round_trips_and_executes",
            test_cobol_return_boolean_round_trips_and_executes},
        {"cobol_return_character_round_trips_and_executes",
            test_cobol_return_character_round_trips_and_executes},
        {"cobol_return_numeric_round_trips_and_executes",
            test_cobol_return_numeric_round_trips_and_executes}
    };

    if (count)
        *count = sizeof(tests) / sizeof(tests[0]);
    return (tests);
}
