#include "cblc_transpiler.hpp"

#define TRANSPILE_STANDARD_LIBRARY_ENTRY(name, buffer, program, result_kind, result_type, \
        parameters, hidden_outputs, failure, generator) \
    {name, buffer, program, result_kind, result_type, parameters, hidden_outputs, failure, 1u, generator}

static const t_transpiler_standard_library_entry g_transpiler_standard_library_entries[] = {
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::abs", TRANSPILE_STANDARD_LIBRARY_BUFFER_NONE,
        "CBLC-ABS", TRANSPILE_STANDARD_LIBRARY_RETURN_INT, "int", "int operand",
        "CBLC-RETURN-F; CBLC-EX-CONTEXT", TRANSPILE_STANDARD_LIBRARY_FAILURE_THROWS,
        transpiler_standard_library_generate_abs),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::atoi", TRANSPILE_STANDARD_LIBRARY_BUFFER_CHAR,
        "CBLC-ATOI", TRANSPILE_STANDARD_LIBRARY_RETURN_INT, "int", "char *source",
        "CBLC-RETURN-F; CBLC-EX-CONTEXT", TRANSPILE_STANDARD_LIBRARY_FAILURE_NONE,
        transpiler_standard_library_generate_atoi),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::atoi", TRANSPILE_STANDARD_LIBRARY_BUFFER_STRING,
        "CBLC-ATOI-STRING", TRANSPILE_STANDARD_LIBRARY_RETURN_INT, "int", "String source",
        "CBLC-RETURN-F; CBLC-EX-CONTEXT", TRANSPILE_STANDARD_LIBRARY_FAILURE_NONE,
        transpiler_standard_library_generate_atoi_string),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::atol", TRANSPILE_STANDARD_LIBRARY_BUFFER_CHAR,
        "CBLC-ATOL", TRANSPILE_STANDARD_LIBRARY_RETURN_INT, "long", "char *source",
        "CBLC-RETURN-F; CBLC-EX-CONTEXT", TRANSPILE_STANDARD_LIBRARY_FAILURE_NONE,
        transpiler_standard_library_generate_atol),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::atol", TRANSPILE_STANDARD_LIBRARY_BUFFER_STRING,
        "CBLC-ATOL-STRING", TRANSPILE_STANDARD_LIBRARY_RETURN_INT, "long", "String source",
        "CBLC-RETURN-F; CBLC-EX-CONTEXT", TRANSPILE_STANDARD_LIBRARY_FAILURE_NONE,
        transpiler_standard_library_generate_atol_string),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::atoll", TRANSPILE_STANDARD_LIBRARY_BUFFER_CHAR,
        "CBLC-ATOLL", TRANSPILE_STANDARD_LIBRARY_RETURN_INT, "long long", "char *source",
        "CBLC-RETURN-F; CBLC-EX-CONTEXT", TRANSPILE_STANDARD_LIBRARY_FAILURE_NONE,
        transpiler_standard_library_generate_atoll),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::atoll", TRANSPILE_STANDARD_LIBRARY_BUFFER_STRING,
        "CBLC-ATOLL-STRING", TRANSPILE_STANDARD_LIBRARY_RETURN_INT, "long long", "String source",
        "CBLC-RETURN-F; CBLC-EX-CONTEXT", TRANSPILE_STANDARD_LIBRARY_FAILURE_NONE,
        transpiler_standard_library_generate_atoll_string),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::fabs", TRANSPILE_STANDARD_LIBRARY_BUFFER_NONE,
        "CBLC-FABS", TRANSPILE_STANDARD_LIBRARY_RETURN_DOUBLE, "double", "double operand",
        "CBLC-RETURN-F; CBLC-EX-CONTEXT", TRANSPILE_STANDARD_LIBRARY_FAILURE_NONE,
        transpiler_standard_library_generate_fabs),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::floor", TRANSPILE_STANDARD_LIBRARY_BUFFER_NONE,
        "CBLC-FLOOR", TRANSPILE_STANDARD_LIBRARY_RETURN_DOUBLE, "double", "double operand",
        "CBLC-RETURN-F; CBLC-EX-CONTEXT", TRANSPILE_STANDARD_LIBRARY_FAILURE_NONE,
        transpiler_standard_library_generate_floor),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::ceil", TRANSPILE_STANDARD_LIBRARY_BUFFER_NONE,
        "CBLC-CEIL", TRANSPILE_STANDARD_LIBRARY_RETURN_DOUBLE, "double", "double operand",
        "CBLC-RETURN-F; CBLC-EX-CONTEXT", TRANSPILE_STANDARD_LIBRARY_FAILURE_NONE,
        transpiler_standard_library_generate_ceil),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::exp", TRANSPILE_STANDARD_LIBRARY_BUFFER_NONE,
        "CBLC-EXP", TRANSPILE_STANDARD_LIBRARY_RETURN_DOUBLE, "double", "double operand",
        "CBLC-RETURN-F; CBLC-EX-CONTEXT", TRANSPILE_STANDARD_LIBRARY_FAILURE_THROWS,
        transpiler_standard_library_generate_exp),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::log", TRANSPILE_STANDARD_LIBRARY_BUFFER_NONE,
        "CBLC-LOG", TRANSPILE_STANDARD_LIBRARY_RETURN_DOUBLE, "double", "double operand",
        "CBLC-RETURN-F; CBLC-EX-CONTEXT", TRANSPILE_STANDARD_LIBRARY_FAILURE_THROWS,
        transpiler_standard_library_generate_log),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::sin", TRANSPILE_STANDARD_LIBRARY_BUFFER_NONE,
        "CBLC-SIN", TRANSPILE_STANDARD_LIBRARY_RETURN_DOUBLE, "double", "double operand",
        "CBLC-RETURN-F; CBLC-EX-CONTEXT", TRANSPILE_STANDARD_LIBRARY_FAILURE_NONE,
        transpiler_standard_library_generate_sin),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::cos", TRANSPILE_STANDARD_LIBRARY_BUFFER_NONE,
        "CBLC-COS", TRANSPILE_STANDARD_LIBRARY_RETURN_DOUBLE, "double", "double operand",
        "CBLC-RETURN-F; CBLC-EX-CONTEXT", TRANSPILE_STANDARD_LIBRARY_FAILURE_NONE,
        transpiler_standard_library_generate_cos),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::tan", TRANSPILE_STANDARD_LIBRARY_BUFFER_NONE,
        "CBLC-TAN", TRANSPILE_STANDARD_LIBRARY_RETURN_DOUBLE, "double", "double operand",
        "CBLC-RETURN-F; CBLC-EX-CONTEXT", TRANSPILE_STANDARD_LIBRARY_FAILURE_NONE,
        transpiler_standard_library_generate_tan),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::round", TRANSPILE_STANDARD_LIBRARY_BUFFER_NONE,
        "CBLC-ROUNDED", TRANSPILE_STANDARD_LIBRARY_RETURN_DOUBLE, "double", "double operand",
        "CBLC-RETURN-F; CBLC-EX-CONTEXT", TRANSPILE_STANDARD_LIBRARY_FAILURE_NONE,
        transpiler_standard_library_generate_rounded),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("cblc::banker_round", TRANSPILE_STANDARD_LIBRARY_BUFFER_NONE,
        "CBLC-BANKER-ROUND", TRANSPILE_STANDARD_LIBRARY_RETURN_DOUBLE, "double",
        "double operand, int scale", "CBLC-RETURN-F; CBLC-EX-CONTEXT",
        TRANSPILE_STANDARD_LIBRARY_FAILURE_THROWS, transpiler_standard_library_generate_banker_round),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("cblc::date_parse_yyyymmdd",
        TRANSPILE_STANDARD_LIBRARY_BUFFER_CHAR, "CBLC-DATE-PARSE-RESULT",
        TRANSPILE_STANDARD_LIBRARY_RETURN_RESULT_OBJECT, "DateParseResult", "char *input",
        "CBLC-RETURN-STRUCT; CBLC-EX-CONTEXT", TRANSPILE_STANDARD_LIBRARY_FAILURE_RESULT_OBJECT,
        transpiler_standard_library_generate_date_parse_result),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("cblc::date_parse_yyyymmdd_legacy",
        TRANSPILE_STANDARD_LIBRARY_BUFFER_CHAR, "CBLC-DATE-YYYYMMDD",
        TRANSPILE_STANDARD_LIBRARY_RETURN_MULTI_OUTPUT, "void", "char *input",
        "year; month; day; packed; serial; status", TRANSPILE_STANDARD_LIBRARY_FAILURE_COMPATIBILITY,
        transpiler_standard_library_generate_date_yyyymmdd),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("cblc::parse_int",
        TRANSPILE_STANDARD_LIBRARY_BUFFER_CHAR, "CBLC-PARSE-INT-RESULT",
        TRANSPILE_STANDARD_LIBRARY_RETURN_RESULT_OBJECT, "ParseIntResult",
        "char *source, int source_length", "CBLC-RETURN-STRUCT; CBLC-EX-CONTEXT",
        TRANSPILE_STANDARD_LIBRARY_FAILURE_RESULT_OBJECT,
        transpiler_standard_library_generate_parse_int_result),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("cblc::parse_double",
        TRANSPILE_STANDARD_LIBRARY_BUFFER_CHAR, "CBLC-PARSE-DOUBLE-RESULT",
        TRANSPILE_STANDARD_LIBRARY_RETURN_RESULT_OBJECT, "ParseDoubleResult",
        "char *source, int source_length", "CBLC-RETURN-STRUCT; CBLC-EX-CONTEXT",
        TRANSPILE_STANDARD_LIBRARY_FAILURE_RESULT_OBJECT,
        transpiler_standard_library_generate_parse_double_result),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("cblc::date_duration_days",
        TRANSPILE_STANDARD_LIBRARY_BUFFER_NONE, "CBLC-DATE-DURATION",
        TRANSPILE_STANDARD_LIBRARY_RETURN_INT, "int", "int start_serial, int end_serial",
        "CBLC-RETURN-F; CBLC-EX-CONTEXT", TRANSPILE_STANDARD_LIBRARY_FAILURE_NONE,
        transpiler_standard_library_generate_date_duration),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::strlen", TRANSPILE_STANDARD_LIBRARY_BUFFER_CHAR,
        "CBLC-STRLEN", TRANSPILE_STANDARD_LIBRARY_RETURN_INT, "int", "char *source",
        "CBLC-RETURN-F; CBLC-EX-CONTEXT", TRANSPILE_STANDARD_LIBRARY_FAILURE_NONE,
        transpiler_standard_library_generate_strlen),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::strlen", TRANSPILE_STANDARD_LIBRARY_BUFFER_STRING,
        "CBLC-STRLEN-STRING", TRANSPILE_STANDARD_LIBRARY_RETURN_INT, "int", "String source",
        "CBLC-RETURN-F; CBLC-EX-CONTEXT", TRANSPILE_STANDARD_LIBRARY_FAILURE_NONE,
        transpiler_standard_library_generate_strlen_string),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::strnlen", TRANSPILE_STANDARD_LIBRARY_BUFFER_CHAR,
        "CBLC-STRNLEN", TRANSPILE_STANDARD_LIBRARY_RETURN_INT, "int",
        "char *source, int request", "CBLC-RETURN-F; CBLC-EX-CONTEXT",
        TRANSPILE_STANDARD_LIBRARY_FAILURE_NONE, transpiler_standard_library_generate_strnlen),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::strnlen", TRANSPILE_STANDARD_LIBRARY_BUFFER_STRING,
        "CBLC-STRNLEN-STRING", TRANSPILE_STANDARD_LIBRARY_RETURN_INT, "int",
        "String source, int request", "CBLC-RETURN-F; CBLC-EX-CONTEXT",
        TRANSPILE_STANDARD_LIBRARY_FAILURE_NONE, transpiler_standard_library_generate_strnlen_string),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::strcmp", TRANSPILE_STANDARD_LIBRARY_BUFFER_CHAR,
        "CBLC-STRCMP", TRANSPILE_STANDARD_LIBRARY_RETURN_INT, "int",
        "char *first, char *second", "CBLC-RETURN-F; CBLC-EX-CONTEXT",
        TRANSPILE_STANDARD_LIBRARY_FAILURE_NONE, transpiler_standard_library_generate_strcmp),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::strcmp", TRANSPILE_STANDARD_LIBRARY_BUFFER_STRING,
        "CBLC-STRCMP-STRING", TRANSPILE_STANDARD_LIBRARY_RETURN_INT, "int",
        "String first, String second", "CBLC-RETURN-F; CBLC-EX-CONTEXT",
        TRANSPILE_STANDARD_LIBRARY_FAILURE_NONE, transpiler_standard_library_generate_strcmp_string),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::strcpy", TRANSPILE_STANDARD_LIBRARY_BUFFER_CHAR,
        "CBLC-STRCPY", TRANSPILE_STANDARD_LIBRARY_RETURN_VOID, "void",
        "char *destination, char *source", "status", TRANSPILE_STANDARD_LIBRARY_FAILURE_COMPATIBILITY,
        transpiler_standard_library_generate_strcpy),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::strcpy", TRANSPILE_STANDARD_LIBRARY_BUFFER_STRING,
        "CBLC-STRCPY-STRING", TRANSPILE_STANDARD_LIBRARY_RETURN_VOID, "void",
        "String destination, String source", "", TRANSPILE_STANDARD_LIBRARY_FAILURE_THROWS,
        transpiler_standard_library_generate_strcpy_string),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::strncpy", TRANSPILE_STANDARD_LIBRARY_BUFFER_CHAR,
        "CBLC-STRNCPY", TRANSPILE_STANDARD_LIBRARY_RETURN_VOID, "void",
        "char *destination, char *source, int request", "status",
        TRANSPILE_STANDARD_LIBRARY_FAILURE_COMPATIBILITY, transpiler_standard_library_generate_strncpy),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::strncpy", TRANSPILE_STANDARD_LIBRARY_BUFFER_STRING,
        "CBLC-STRNCPY-STRING", TRANSPILE_STANDARD_LIBRARY_RETURN_VOID, "void",
        "String destination, String source, int request", "", TRANSPILE_STANDARD_LIBRARY_FAILURE_THROWS,
        transpiler_standard_library_generate_strncpy_string),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::memcmp", TRANSPILE_STANDARD_LIBRARY_BUFFER_CHAR,
        "CBLC-MEMCMP", TRANSPILE_STANDARD_LIBRARY_RETURN_INT, "int",
        "char *first, char *second, int count", "CBLC-RETURN-F; CBLC-EX-CONTEXT",
        TRANSPILE_STANDARD_LIBRARY_FAILURE_NONE, transpiler_standard_library_generate_memcmp),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::memcmp", TRANSPILE_STANDARD_LIBRARY_BUFFER_STRING,
        "CBLC-MEMCMP-STRING", TRANSPILE_STANDARD_LIBRARY_RETURN_INT, "int",
        "String first, String second, int count", "CBLC-RETURN-F; CBLC-EX-CONTEXT",
        TRANSPILE_STANDARD_LIBRARY_FAILURE_NONE, transpiler_standard_library_generate_memcmp_string),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::strcat", TRANSPILE_STANDARD_LIBRARY_BUFFER_CHAR,
        "CBLC-STRCAT", TRANSPILE_STANDARD_LIBRARY_RETURN_VOID, "void",
        "char *destination, char *left, char *right", "status; result_length",
        TRANSPILE_STANDARD_LIBRARY_FAILURE_COMPATIBILITY, transpiler_standard_library_generate_strcat),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::strcat", TRANSPILE_STANDARD_LIBRARY_BUFFER_STRING,
        "CBLC-STRCAT-STRING", TRANSPILE_STANDARD_LIBRARY_RETURN_VOID, "void",
        "String destination, String left, String right", "", TRANSPILE_STANDARD_LIBRARY_FAILURE_THROWS,
        transpiler_standard_library_generate_strcat_string),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::strtod", TRANSPILE_STANDARD_LIBRARY_BUFFER_CHAR,
        "CBLC-STRTOD", TRANSPILE_STANDARD_LIBRARY_RETURN_DOUBLE, "double", "char *source",
        "CBLC-RETURN-F; CBLC-EX-CONTEXT", TRANSPILE_STANDARD_LIBRARY_FAILURE_THROWS,
        transpiler_standard_library_generate_strtod),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::strtod", TRANSPILE_STANDARD_LIBRARY_BUFFER_STRING,
        "CBLC-STRTOD-STRING", TRANSPILE_STANDARD_LIBRARY_RETURN_DOUBLE, "double", "String source",
        "CBLC-RETURN-F; CBLC-EX-CONTEXT", TRANSPILE_STANDARD_LIBRARY_FAILURE_THROWS,
        transpiler_standard_library_generate_strtod_string),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::pow", TRANSPILE_STANDARD_LIBRARY_BUFFER_NONE,
        "CBLC-POWEROF", TRANSPILE_STANDARD_LIBRARY_RETURN_DOUBLE, "double",
        "double base, double exponent", "CBLC-RETURN-F; CBLC-EX-CONTEXT",
        TRANSPILE_STANDARD_LIBRARY_FAILURE_THROWS, transpiler_standard_library_generate_powerof),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::sqrt", TRANSPILE_STANDARD_LIBRARY_BUFFER_NONE,
        "CBLC-SQRT", TRANSPILE_STANDARD_LIBRARY_RETURN_DOUBLE, "double", "double operand",
        "CBLC-RETURN-F; CBLC-EX-CONTEXT", TRANSPILE_STANDARD_LIBRARY_FAILURE_THROWS,
        transpiler_standard_library_generate_sqrt),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::fmin", TRANSPILE_STANDARD_LIBRARY_BUFFER_NONE,
        "CBLC-MIN", TRANSPILE_STANDARD_LIBRARY_RETURN_DOUBLE, "double",
        "double left, double right", "CBLC-RETURN-F; CBLC-EX-CONTEXT",
        TRANSPILE_STANDARD_LIBRARY_FAILURE_NONE, transpiler_standard_library_generate_min),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::fmax", TRANSPILE_STANDARD_LIBRARY_BUFFER_NONE,
        "CBLC-MAX", TRANSPILE_STANDARD_LIBRARY_RETURN_DOUBLE, "double",
        "double left, double right", "CBLC-RETURN-F; CBLC-EX-CONTEXT",
        TRANSPILE_STANDARD_LIBRARY_FAILURE_NONE, transpiler_standard_library_generate_max),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::toupper", TRANSPILE_STANDARD_LIBRARY_BUFFER_CHAR,
        "CBLC-TOUPPER", TRANSPILE_STANDARD_LIBRARY_RETURN_CHAR_POINTER, "char *",
        "char *text", "CBLC-RETURN-PTR; CBLC-EX-CONTEXT", TRANSPILE_STANDARD_LIBRARY_FAILURE_NONE,
        transpiler_standard_library_generate_toupper),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::toupper", TRANSPILE_STANDARD_LIBRARY_BUFFER_STRING,
        "CBLC-TOUPPER-STRING", TRANSPILE_STANDARD_LIBRARY_RETURN_VOID, "void",
        "String text", "", TRANSPILE_STANDARD_LIBRARY_FAILURE_THROWS,
        transpiler_standard_library_generate_toupper_string),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::tolower", TRANSPILE_STANDARD_LIBRARY_BUFFER_CHAR,
        "CBLC-TOLOWER", TRANSPILE_STANDARD_LIBRARY_RETURN_CHAR_POINTER, "char *",
        "char *text", "CBLC-RETURN-PTR; CBLC-EX-CONTEXT", TRANSPILE_STANDARD_LIBRARY_FAILURE_NONE,
        transpiler_standard_library_generate_tolower),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::tolower", TRANSPILE_STANDARD_LIBRARY_BUFFER_STRING,
        "CBLC-TOLOWER-STRING", TRANSPILE_STANDARD_LIBRARY_RETURN_VOID, "void",
        "String text", "", TRANSPILE_STANDARD_LIBRARY_FAILURE_THROWS,
        transpiler_standard_library_generate_tolower_string),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::isdigit", TRANSPILE_STANDARD_LIBRARY_BUFFER_NONE,
        "CBLC-ISDIGIT", TRANSPILE_STANDARD_LIBRARY_RETURN_INT, "int", "char current",
        "CBLC-RETURN-F; CBLC-EX-CONTEXT", TRANSPILE_STANDARD_LIBRARY_FAILURE_NONE,
        transpiler_standard_library_generate_isdigit),
    TRANSPILE_STANDARD_LIBRARY_ENTRY("std::isalpha", TRANSPILE_STANDARD_LIBRARY_BUFFER_NONE,
        "CBLC-ISALPHA", TRANSPILE_STANDARD_LIBRARY_RETURN_INT, "int", "char current",
        "CBLC-RETURN-F; CBLC-EX-CONTEXT", TRANSPILE_STANDARD_LIBRARY_FAILURE_NONE,
        transpiler_standard_library_generate_isalpha)
};

#undef TRANSPILE_STANDARD_LIBRARY_ENTRY

const t_transpiler_standard_library_entry *transpiler_standard_library_get_entries(size_t *count)
{
    if (count)
        *count = sizeof(g_transpiler_standard_library_entries) / sizeof(g_transpiler_standard_library_entries[0]);
    return (g_transpiler_standard_library_entries);
}

const t_transpiler_standard_library_entry *transpiler_standard_library_lookup(const char *qualified_name)
{
    return (transpiler_standard_library_lookup_with_buffer_kind(qualified_name,
        TRANSPILE_STANDARD_LIBRARY_BUFFER_NONE));
}

const t_transpiler_standard_library_entry *transpiler_standard_library_lookup_with_buffer_kind(
    const char *qualified_name, t_transpiler_standard_library_buffer_kind buffer_kind)
{
    const t_transpiler_standard_library_entry *entries;
    size_t entry_count;
    size_t index;

    if (!qualified_name)
        return (NULL);
    entries = transpiler_standard_library_get_entries(&entry_count);
    index = 0;
    while (index < entry_count)
    {
        if (std::strncmp(entries[index].qualified_name, qualified_name,
                std::strlen(entries[index].qualified_name) + 1) == 0)
        {
            if (buffer_kind == TRANSPILE_STANDARD_LIBRARY_BUFFER_NONE
                || entries[index].buffer_kind == buffer_kind)
                return (&entries[index]);
        }
        index += 1;
    }
    return (NULL);
}
